//! Mock implementation of [`EnvironmentRepository`] for unit tests.
//!
//! The `MockEnvironmentRepository` type is generated by `#[mockall::automock]`
//! on the trait in [`super`]. Import it in tests as:
//! ```ignore
//! use crate::repositories::environment::mock::MockEnvironmentRepository;
//! ```

#[cfg(test)]
pub use super::MockEnvironmentRepository;
