argo-cd:
  enabled: true
  configs:
    params:
      server.insecure: true

api:
  image: mahakam-api
  tag: latest
  imagePullPolicy: IfNotPresent
  databaseUrl: sqlite:///data/mahakam.db
  workspacesBasePath: /app/workspaces/base
  viewerImage: mahakam-ttyd:latest
  browserViewerImage: mahakam-browser-viewer:latest
  androidViewerImage: mahakam-android-viewer:latest

web:
  image: mahakam-web
  tag: latest
  imagePullPolicy: IfNotPresent
