//! Mock implementation of [`WorkspaceRepository`] for unit tests.
//!
//! The `MockWorkspaceRepository` type is generated by `#[mockall::automock]`
//! on the trait in [`super`]. Import it in tests as:
//! ```ignore
//! use crate::repositories::workspace::mock::MockWorkspaceRepository;
//! ```

#[cfg(test)]
pub use super::MockWorkspaceRepository;
